<?php
//zskj0328
$enumdata=array(
	'shoplevel'=>array(//消费水平
		array('key'=>'低端','txt'=>'低端'),
		array('key'=>'工薪','txt'=>'工薪'),
		array('key'=>'小资','txt'=>'小资'),
		array('key'=>'中高档','txt'=>'中高档'),
		array('key'=>'高档','txt'=>'高档'),
		array('key'=>'奢华','txt'=>'奢华'),
	),
	'trades'=>array(//行业类别
		array('key'=>'餐饮','txt'=>'餐饮'),
		array('key'=>'酒店','txt'=>'酒店'),
		array('key'=>'咖啡厅','txt'=>'咖啡厅'),
		array('key'=>'足浴','txt'=>'足浴'),
		array('key'=>'KTV','txt'=>'KTV'),
		array('key'=>'购物商超','txt'=>'购物商超'),
		array('key'=>'酒店宾馆','txt'=>'酒店宾馆'),
		array('key'=>'休闲娱乐','txt'=>'休闲娱乐'),
	),
	'authmode'=>array(//认证方式
		array('key'=>'0','txt'=>'注册认证','code'=>'reg'),
		array('key'=>'1','txt'=>'手机认证','code'=>'phone'),
		array('key'=>'2','txt'=>'无需认证','code'=>'allow'),
		// array('key'=>'3','txt'=>'微信密码认证','code'=>'wecha'),
		array('key'=>'4','txt'=>'微信关注认证','code'=>'wecha_follow'),
	),
);
?>